services:
  backend:
    build:
      context: ./server/app  # Adjust this path to where your backend Dockerfile is located
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL_NAME: ${GROQ_MODEL_NAME}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LOCAL_LLM: ${LOCAL_LLM}
      TOKENIZERS_PARALLELISM: ${TOKENIZERS_PARALLELISM}
    env_file:
      - .env

  frontend:
    build:
      context: ./client/static  # Adjust this path to where your frontend Dockerfile is located
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      REACT_APP_API_URL: http://backend:8000
    env_file:
      - .env