FROM python:3.9-slim
WORKDIR /app

COPY pyproject.toml requirements.txt ./

EXPOSE 8000

ARG GROQ_API_KEY
ENV GROQ_API_KEY=$GROQ_API_KEY

ARG GROQ_MODEL_NAME
ENV GROQ_MODEL_NAME=$GROQ_MODEL_NAME

ARG TAVILY_API_KEY
ENV TAVILY_API_KEY=$TAVILY_API_KEY

ARG LOCAL_LLM
ENV LOCAL_LLM=$LOCAL_LLM

ARG TOKENIZERS_PARALLELISM
ENV TOKENIZERS_PARALLELISM=$TOKENIZERS_PARALLELISM

# Install dependencies
RUN pip install -r requirements.txth || pip install hatch 

COPY . .

RUN cd src

CMD ["hatch", "run", "dev:uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# RUN pip install hatch && hatch install || pip install -r requirements.txt




